# Generated by Django 5.0.6 on 2024-05-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='title',
            new_name='actor',
        ),
        migrations.RemoveField(
            model_name='show',
            name='description',
        ),
        migrations.AddField(
            model_name='show',
            name='director',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='genres',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='movies',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
