# Generated by Django 5.0.6 on 2024-05-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0002_rename_title_show_actor_remove_show_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
