# Generated by Django 5.0.6 on 2024-05-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0003_show_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=models.CharField(choices=[('Action', 'Action'), ('Sports', 'sports'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Comedy', 'comedy'), ('Si-Fi', 'Si-Fi'), ('Thriller', 'Thriller'), ('Biopic', 'Biopic')], default='Action', max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
