# Generated by Django 5.0.6 on 2024-05-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0004_alter_show_genres_alter_show_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='show',
            name='genres',
            field=models.CharField(choices=[('Action', 'Action'), ('Sports', 'Sports'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Si-Fi', 'Si-Fi'), ('Thriller', 'Thriller'), ('Biopic', 'Biopic')], default='Action', max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
