# Generated by Django 5.0.6 on 2024-06-08 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
