# Generated by Django 5.0.6 on 2024-06-09 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0007_remove_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='fullname',
        ),
    ]
