# Generated by Django 5.0.6 on 2024-06-09 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myshow', '0008_rename_username_profile_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fullname',
            new_name='username',
        ),
    ]
